CREATE DATABASE EMPLOYEE;

USE EMPLOYEE;
CREATE TABLE DEPARTMENT(
DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME  VARCHAR(255));
INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES(
1,'HUMAN RESOURCE');
INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES(
2,'DESIGN');
INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES(
3,'TECHNICAL');
INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES(
4,'CONTENT');
SELECT * FROM DEPARTMENT;

CREATE TABLE EMPLOYEE(
EMPLOYEE_ID INT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(255),
SALARY INT,
DEPARTMENT_ID INT,
FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);
INSERT INTO 
EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_NAME,SALARY,DEPARTMENT_ID) 
VALUES(1,'JEAN',15000,1);
INSERT INTO
EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_NAME,SALARY,DEPARTMENT_ID) 
VALUES(2,'KYLE',11000,2);
INSERT INTO
EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_NAME,SALARY,DEPARTMENT_ID) 
VALUES(3,'LINA',17000,3);
INSERT INTO
EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_NAME,SALARY,DEPARTMENT_ID) 
VALUES(4,'NEIL',14000,4);


-- QUERIES
SELECT E.EMPLOYEE_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME FROM 
EMPLOYEE E, DEPARTMENT D WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID; 

SELECT EMPLOYEE_NAME, SALARY FROM EMPLOYEE ORDER BY SALARY DESC;

SELECT AVG(E.SALARY) AS AVG_SALARY,D.DEPARTMENT_NAME FROM employee E,
DEPARTMENT D WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID GROUP BY DEPARTMENT_NAME;